### ISSUE TITLE
Create alert - RabbitMqClusterNotAllNodesRunning

### ISSUE THREAD

**Issue by rasheedamir** [stakater/rabbitmq-observability-chart#6]
```
      - alert: RabbitMqClusterNotAllNodesRunning
        expr: (sum(rabbitmq_up{job=~".*rabbitmq.*"})  by (job))  < (sum(up{job=~".*rabbitmq.*"})  by (job))
        for: <%= p('rabbitmq_alerts.rabbitmq_up.evaluation_time') %>
        labels:
          job: rabbitmq
          severity: critical
        annotations:
          description: Some RabbitMQ Cluster Nodes Are Down in job {{`{{ $labels.instance }}`}}/{{`{{ $labels.job}}`}}
          summary: Some RabbitMQ Cluster Nodes Are Down in job {{`{{ $labels.instance }}`}}/{{`{{ $labels.job}}`}}
```
