### ISSUE TITLE
Create alert - RabbitMQServerDown

### ISSUE THREAD

**Issue by rasheedamir** [stakater/rabbitmq-observability-chart#7]
```
      - alert: RabbitMQServerDown
        expr: min(rabbitmq_up) by(instance) != 1
        for: <%= p('rabbitmq_alerts.server_down.evaluation_time') %>
        labels:
          service: rabbitmq
          severity: critical
        annotations:
          summary: "Rabbitmq Server instance `{{$labels.instance}}` is down"
          description: "The RabbitMQ Server instance at `{{$labels.instance}}` has been down the last <%= p('rabbitmq_alerts.server_down.evaluation_time') %>"

```
